# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-app-deployment
  labels:
    app: recipe-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: recipe-app
  template:
    metadata:
      labels:
        app: recipe-app
    spec:
      containers:
      - name: recipe-app
        image: recipe-app-image:latest
        ports:
        - containerPort: 5000
        env:
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017"
